insert into alim_groupe(alim_grp_code,alim_grp_nom_fr) values ('04','viandes, œufs, poissons et assimilés');
insert into alim_groupe(alim_grp_code,alim_grp_nom_fr) values ('10','aides culinaires et ingrédients divers');
insert into alim_ssgroupe(alim_ss_grp_code,alim_ss_grp_nom_fr) values ('1004','céréales et biscuits infantiles');
insert into alim_ssgroupe(alim_ss_grp_code,alim_ss_grp_nom_fr) values ('0408','mollusques et crustacés crus');
insert into alim_ssssgroupe(alim_ss_ss_grp_code,alim_ss_ss_grp_nom_fr) values ('000000',' ');
insert into composition_acides_gras values(3043,' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ');
insert into composition_autres values (3043,' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ');
insert into composition_energie values (3043, ' ',' ',' ',' ');
insert into composition_vitamine values (3043, ' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ');
insert into aliment values ('10001','Calmar ou calamar ou encornet cru','Loligo vulgaris','04','0408','000000',3043,3043,3043,3043);
insert into aliment values ('11083','Sel marin gris non iodé non fluoré',' ','10','1004','000000',3043,3043,3043,3043);
